rundeck:
  rpm: http://repo.rundeck.org/latest.rpm
  jdbcdriver:
    url: http://download.oracle.com/otn/utilities_drivers/jdbc/10205/ojdbc14.jar
    filename: ojdbc14.jar
  config:
    host: "{{ inventory_hostname }}"
    web_context: rundeck
  db:
    schema: rundeck
    user: rundeck
    password: rundeck
    host: localhost
  plugins:
    directory: /var/lib/rundeck/libext/
    copyfile:
      ec2-nodes:
        repo: https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/releases/download/v1.5.1/rundeck-ec2-nodes-plugin-1.5.1.jar
        filename: rundeck-ec2-nodes-plugin-1.5.1.jar
    build:
      slack-incoming-webhook:
        repo: https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin.git
        directory: rundeck-slack-incoming-webhook-plugin
        filename: rundeck-slack-incoming-webhook-plugin-0.5.jar


